package Lesson_2;

public class Unicode {

	/**
	 * @Description
	 * @author Administrator
	 * @param args void
	 * 2014-3-12
	 * Generated by the IBM IDL-to-Java compiler, version 1.0 
	 * from F:\TestRoot\apps\a1\ units\include\PolicyHome.idl 
	 * Wednesday, June 17, 1998 6:44:40 o¡¯clock AM GMT+00:00 
	 */
	/*
	 * If the space of code in 11 line between "\" and "units" isn't there.
	 * The code will cannot compile.Because unicode the priority is higher than character even more in note.
	 */
	public static void main(String[] args) {
		System.out.print("Hell");  
        System.out.println("o world"); 
	}

}
